# Site settings
title: ingusmat|dot|com
email: ingus@gm@il.com
description: > # this means to ignore newlines until "baseurl:"
  PHP Symfony2 engineer at Quizzle, Rails developer at large, Autism daddy, infrequent wargamer, occasional rocker and roller.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ingusmat.com" # the base hostname & protocol for your site
twitter_username: ingusmat
github_username:  ingusmat

# Build settings
markdown: kramdown
